# ==== Config file for running the 10x Cell Ranger pipeline ====================


# Path to the fastq directory, multiple directories can be given.
RAW_DATA:
    - "raw_data"


# A list of sample names. This will be the name of the output folder. All sample 
# names must be unique. There must be the same number of sample names as RNA_samples
# below.
SAMPLES:
    - "JH313-15_AG"
    - "JH313-15_NF"
    - "JH313-15_OF"
    - "JH313-15_DB"
    - "JH313-15_MH"
    - "JH313-15_FD"
    - "JH313-15_JB"
    - "JH313-15_PH"
    - "JH310-12_BH"
    - "JH310-12_MV"
    - "JH310-12_NG"
    - "JH310-12_FG"
    - "JH310-12_AP"
    - "JH310-12_CP"
    - "JH310-12_EB"
    - "JH310-12_TS"

# Sample names separated by groups to aggregate. If no samples to aggregate,
# leave this blank. Structure is as follows:
# AGGR_SAMPLES:
#   GROUP_NAME:
#      - "samplex"...
AGGR_SAMPLES:

# Sample names for gene expression fastqs. If the same libraries were
# sequenced multiple times, just include all the fastq directories in the
# RAW_DATA list and make sure the fastqs from all runs begin with the
# sample name. Only fastqs that begin with the sample name will be 
# included in the analysis.
RNA_SAMPLES:
    - "JH313_AG"
    - "JH313_NF"
    - "JH313_OF"
    - "JH313_DB"
    - "JH313_MH"
    - "JH313_FD"
    - "JH313_JB"
    - "JH313_PH"
    - "JH310-12_BH-GEX"
    - "JH310-12_MV-GEX"
    - "JH310-12_NG-GEX"
    - "JH310-12_FG-GEX"
    - "JH310-12_AP-GEX"
    - "JH310-12_CP-GEX"
    - "JH310-12_EB-GEX"
    - "JH310-12_TS-GEX"

# Sample names for CITE-seq and cell hashing fastqs. If 
# the libraries were sequenced multiple times, just make sure the fastqs 
# from all runs begin with the sample name. If CITE-seq or cell hashing 
# was not performed, leave this blank. If you have CITE-seq on only a
# a subset of samples, keep the slot empty (ex. - "")
ADT_SAMPLES:
    - "JH314_AG"
    - "JH314_NF"
    - "JH314_OF"
    - "JH314_DB"
    - "JH314_MH"
    - "JH314_FD"
    - "JH314_JB"
    - "JH314_PH"
    - "JH310-12_BH-FB"
    - "JH310-12_MV-FB"
    - "JH310-12_NG-FB"
    - "JH310-12_FG-FB"
    - "JH310-12_AP-FB"
    - "JH310-12_CP-FB"
    - "JH310-12_EB-FB"
    - "JH310-12_TS-FB"

# Sample names for TCR VDJ fastqs. Follow the same parameters required for gene
# expression fastqs. If VDJ sequencing was not performed, leave this blank.
VDJ_T_SAMPLES:


# Sample names for BCR VDJ fastqs. Follow the same parameters required for gene
# expression fastqs. If VDJ sequencing was not performed, leave this blank.
VDJ_B_SAMPLES:
    - "JH315_AG"
    - "JH315_NF"
    - "JH315_OF"
    - "JH315_DB"
    - "JH315_MH"
    - "JH315_FD"
    - "JH315_JB"
    - "JH315_PH"
    - "JH310-12_BH-VDJ"
    - "JH310-12_MV-VDJ"
    - "JH310-12_NG-VDJ"
    - "JH310-12_FG-VDJ"
    - "JH310-12_AP-VDJ"
    - "JH310-12_CP-VDJ"
    - "JH310-12_EB-VDJ"
    - "JH310-12_TS-VDJ"

# Path to the output directory.
RESULTS:
    "results"

# Path to the Cell Ranger genome reference.
GENOME:
    "/beevol/home/rbilab/ref/cellranger/human/refdata-gex-GRCh38-2020-A"

# Path to the antibody reference table used to extract the antibody name 
# and barcode. If CITE-seq or cell hashing was not performed, leave this 
# blank.
ADT_REF:
    "files/antibodies.csv"

# Path to the Cell Ranger VDJ reference. If VDJ sequencing was not performed,
# leave this blank.
VDJ_REF:
    "/beevol/home/rbilab/ref/cellranger/human/refdata-cellranger-vdj-GRCh38-alts-ensembl-5.0.0"

# Maximum number of jobs per sample that can be submitted by Cell Ranger
# at a time.
MAX_JOBS:
    24

# Path to an LSF template, this is optional.
LSF_TEMPLATE:
    "lsf.template"

# Arguments to pass for chemistry. Only use this if the run failed.
CHEMISTRY:
    

VELOCYTO_GROUP:


IMMCANTATION_CONTAINER:
    "/beevol/home/wellskri/Analysis/Mia_Smith/Catherine_Nicolas/full_antigen_pos_data/docker/immcantation/immcantation.sif"

# =============================================================================== #

# Config for running R scripts
SCRIPT_PATH:
    "src/scripts"

# Path to all scripts to run, put these in the order you want them run.
SCRIPTS_RUN:
    # JR_initial_processing: "JH307_JR/01_Initial_processing.R"
    # JR_doublets: "JH307_JR/02_remove_doublets.R"
    # JR_adt_norm: "JH307_JR/03_adt_dsb_normalization.R"
    # JR_PCA_UMAP: "JH307_JR/04_PCA_UMAP.R"
    # JR_name_clusters: "JH307_JR/05_name_clusters.R"
    # JR_adt_gating: "JH307_JR/06_adt_gating.R"
    # JR_check_published: "JH307_JR/09_check_against_published.R"

# If the exact same scripts will be run for multiple samples, put them
# here. This is a dictionary with sample and scripts_run as keys.
# Within a sample, the scripts will be run in order, otherwise the
# scripts will be run in parallel. Set to "all" if you want to run
# on all samples
SAMPLE_SCRIPTS:
    samples:
        "all"
    scripts_run:
        - "02_Initial_processing.R"
        - "03_remove_doublets.R"
    #     - "03_adt_dsb_normalization.R"
    #     - "04_PCA_UMAP.R"
    #     - "05_name_clusters.R"
    #     - "06_adt_gating.R"
    #     - "07_PCA_UMAP_subset_cluster.R"
    #     - "08_add_subset_info.R"
    #     - "09_check_against_published.R"

# Path to the metadata for each sample that should be added to the objects.
# Must have a column called "Sample.Name" that has the exact same pattern as
# the sample names here.
SAMPLE_METADATA:
    "files/Deidentified_donor_metadata.xlsx"

# Path to the sample info sheet. This contains the information about if the
# sample has HTOs and ADTs. It is also where you will add in information
# about the number of dimensions and resoultion. See files/sample_info.tsv
# for an example.
SAMPLE_INFO:
    "files/sample_info.tsv"

RSCRIPT_CONTAINER:
    "/beevol/home/wellskri/Analysis/Mia_Smith/Catherine_Nicolas/full_antigen_pos_data/docker/r_docker/catherine_bcells.sif"

DROPKICK_CONTAINER:
    "/beevol/home/wellskri/Analysis/Mia_Smith/Catherine_Nicolas/full_antigen_pos_data/docker/dropkick/dropkick.sif"